[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
rand = { workspace = true }
